### ISSUE TITLE
Support Matrix fields?

### ISSUE THREAD

**Issue by ryanpcmcquen** [venveo/craft-bulkedit#18]
I saw your note in the README about Matrix fields:
>Custom fields and Matrix fields are not currently supported due to issues that arise when a field is rendered without single entry selected.

What work needs to be done for this? This would help my team out a lot and I would love to contribute if possible.

**Comment by Mosnar** [comment]
@ryanpcmcquen So, regarding matrix blocks, the trouble is really just the level of complexity it would introduce. There are some things we could do relatively easily; however, I'm not sure how useful it would be. 

I'd love to hear what kind of use-case you have so we can take a look at what it would involve. My initial thought is that we would really only be able to support actions that are creating new blocks - for example, prepending/appending and replacing all blocks.

Modifying the contents of individual blocks probably isn't feasible, since without some kind of condition-builder, we wouldn't be able to decide which blocks to perform the actions on.

**Comment by Mosnar** [comment]
@ryanpcmcquen after thinking about this for a bit, I decided to revisit it and I think I've come up with a way to make the replacement strategy work on all fields, including Matrix fields. I've also been working on making certain element attributes bulk editable, so I implemented it on that branch.

The attribute editing isn't completed yet, so you won't actually be able to use that feature, but if you want to give the field replacement a try, you're welcome to try setting the bulk-edit composer requirement to this commit: `bba0fcfaffdda453870bfeb9b693d58a1c1dcffc`

**Comment by Mosnar** [comment]
Just released 2.0.2 with this feature.

**Comment by ryanpcmcquen** [comment]
Thank you so much @Mosnar!
