### ISSUE TITLE
Fields with Custom Labels

### ISSUE THREAD

**Issue by ambidustrious** [venveo/craft-bulkedit#35]
I have a few fields that I've customized the label for an entry type. When doing a bulk edit on those fields, it displays the label from the original fields and not the customized label. 

**Original Field**
![image](https://user-images.githubusercontent.com/22107826/126995029-b33b6ac6-499a-48ae-865d-6946658b3515.png)

**Customized Label**
![image](https://user-images.githubusercontent.com/22107826/126994912-4e4dbb71-a846-44e9-ab2a-0538703bb50a.png)

**Bulk Edit still shows original field label**
![image](https://user-images.githubusercontent.com/22107826/126995223-91aced10-78c5-46bb-ab47-8f2b1ccb09ac.png)

**Comment by Mosnar** [comment]
This is actually more difficult to solve than you'd think. The problem is that the sources on the sidebar of the element index can include multiple entry types, each of which have their own field layouts and potential custom field labels. For this reason, there's no way to know which custom field label is the "correct" one to display. 

This is the same reason custom field labels don't appear in the element index tables currently. See related discussion here: https://github.com/craftcms/cms/discussions/8903

Rather than hacking in some half-baked solution, I'd rather wait for the P&T time to come up with a proper solution to this issue.
